### ISSUE TITLE
Core Block & Component Checklist

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#26]
# :sparkles: Block & Component Checklist :sparkles:

This is a list of all blocks, with links to the most recent, or the final pen, as well as links to where each block has gone through QA.

# Blocks

### Banner
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/WKyRzQ)
- [x] Final version of the block has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](https://devsite.carleton.ca/rds/b-banners-banner/)
- [x] Block has gone through the QA process, [view the QA issue here](https://github.com/dannybrown73/rds-docs/issues/27)
- [x] Block has been fully integrated into core
- [x] Block tested in common templates and layouts and integrated with many other RDS blocks.

### Content Block
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/pZxMZb)
- [x] Final version of the block has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](https://devsite.carleton.ca/rds/b-content/)
- [x] Block has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/28)
- [x] Block has been fully integrated into core
- [x] Block tested in common templates and layouts and integrated with many other RDS blocks.

### Footer Brand
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/gjxdVp)
- [x] Final version of the block has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](https://devsite.carleton.ca/rds/b-footer/)
- [x] Block has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/29)
- [x] Block has been fully integrated into core
- [x] Block tested in common templates and layouts and integrated with many other RDS blocks.

### Simple Footer
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/gjxdVp)
- [x] Final version of the block has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](#)
- [x] Block has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/30)
- [x] Block has been fully integrated into core
- [x] Block tested in common templates and layouts and integrated with many other RDS blocks.

### Sitemap Footer
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/gjxdVp)
- [x] Final version of the block has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](#)
- [x] Block has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/31)
- [x] Block has been fully integrated into core
- [x] Block tested in common templates and layouts and integrated with many other RDS blocks.

### Grid View
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/MBXKwO)
- [x] Final version of the block has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](https://devsite.carleton.ca/rds/c-cards-card/)
- [x] Block has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/24)
- [x] Block has been fully integrated into core
- [x] Block tested in common templates and layouts and integrated with many other RDS blocks.

### List View
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/PBeQgX)
- [x] Final version of the block has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](https://devsite.carleton.ca/rds/b-listing-listgroup/)
- [x] Block has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/17)
- [x] Block has been fully integrated into core
- [x] Block tested in common templates and layouts and integrated with many other RDS blocks.

# Components

### Accordion
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/MBZwqO)
- [x] Final version of the component has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](https://devsite.carleton.ca/rds/c-accordion/)
- [x] Component has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/32)
- [x] Component has been fully integrated into core
- [x] Component tested in common templates and layouts and integrated with many other RDS blocks.

### Button
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/yqGare)
- [x] Final version of the component has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](#)
- [x] Component has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/33)
- [x] Component has been fully integrated into core
- [x] Component tested in common templates and layouts and integrated with many other RDS blocks.

### Search Form
Most recent pen: [v 1.0.0](https://codepen.io/cuweb/pen/EpMeGj)
- [x] Final version of the component has been created in codepen, see above for updated link
- [x] Pen has been exported and uploaded to devsite, [view that here](https://devsite.carleton.ca/rds/c-form-search)
- [x] Component has gone through the QA process, [view the checklist](https://github.com/dannybrown73/rds-docs/issues/33)
- [x] Component has been fully integrated into core
- [x] Component tested in common templates and layouts and integrated with many other RDS blocks.

### Cards
See `Grid View` in the `Listing Block` section above

**Comment by troychaplin79** [comment]
Closed, moved to a discussion item in new repo: https://github.com/ravendesignsystem/rds/issues/3
